//! DC-55 end-to-end identity check (RFC item 1c).
//!
//! `tests/fixtures/dc55_pre_swap_repo` is a repository created with the pre-DC-55 `prikk` binary,
//! using the first-party SHA-256 implementation `crates/prikk-hash/src/tests/frozen_outgoing.rs`
//! now freezes. It exercises `prikk_hash::sha256` at all of `id.rs`, `payload/patch.rs`,
//! `wal.rs`, `layout.rs` (ref-name storage keys), `state_root.rs`, and `refs/log.rs` across two
//! WAL/seal cycles, the second including a text edit through `text_span.rs`.
//!
//! This test copies that fixture into a temporary directory and runs `verify` and `doctor` against
//! it using the **current** (post-swap, `sha2`-backed) binary. A clean pass is the one check that
//! exercises every production call site against genuinely persisted bytes, rather than by
//! inference from the unit-level equivalence campaign in `tests::hash_differential`. It stays in
//! the tree as a permanent regression guard — a changed digest at any of the three sites the
//! campaign cannot directly observe (`layout.rs`, `wal.rs`, `refs/log.rs`) would make the fixture
//! fail `verify` here without needing the original pre-swap binary to reproduce.
//!
//! Do not regenerate this fixture. It is frozen for the same reason
//! `crates/prikk-object/src/vectors/snapshot.txt` is not regenerated by DC-55: it is the evidence,
//! not a convenience.
//!
//! **Why `copy_fixture` re-creates empty directories after copying.** Git has no representation
//! for an empty directory, so `RepositoryLayout::required_directories()` entries that happen to be
//! empty at rest (`objects/tag`, `objects/attestation`, `refs/locks`, `refs/tmp`, `cache`,
//! `quarantine` — none of them used by this fixture's two commits) do not survive being committed.
//! A `.gitkeep` placeholder does **not** fix this: prikk's own integrity checking rejects any
//! non-directory entry inside an object-type directory (`unexpected non-directory in object type
//! directory`), so a placeholder would turn this test into a permanent failure instead of a
//! transient one. Recreating the directories at test time — from `required_directories()` itself,
//! not a hand-maintained list — is the only approach that survives both a commit and a future
//! layout change. This does not weaken the identity evidence: empty directories contain no bytes
//! for any hash to cover, so nothing being reconstituted here is part of the identity claim.

#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use prikk_store::RepositoryLayout;

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/dc55_pre_swap_repo"
);

fn prikk(repo: &Path) -> Command {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_prikk"));
    cmd.current_dir(repo);
    cmd
}

fn ok(output: &Output, what: &str) {
    assert!(
        output.status.success(),
        "{what} failed (status {:?})\nstdout: {}\nstderr: {}",
        output.status.code(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}

fn copy_fixture() -> PathBuf {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let mut dest = std::env::temp_dir();
    dest.push(format!("prikk-dc55-e2e-{}-{nanos}", std::process::id()));
    copy_dir(Path::new(FIXTURE), &dest);

    let layout = RepositoryLayout::open(&dest).unwrap();
    for directory in layout.required_directories() {
        std::fs::create_dir_all(directory).unwrap();
    }

    dest
}

fn copy_dir(src: &Path, dest: &Path) {
    std::fs::create_dir_all(dest).unwrap();
    for entry in std::fs::read_dir(src).unwrap() {
        let entry = entry.unwrap();
        let dest_path = dest.join(entry.file_name());
        if entry.file_type().unwrap().is_dir() {
            copy_dir(&entry.path(), &dest_path);
        } else {
            std::fs::copy(entry.path(), &dest_path).unwrap();
        }
    }
}

#[test]
fn post_swap_binary_verifies_pre_swap_repository_clean() {
    let repo = copy_fixture();

    let out = prikk(&repo).arg("verify").output().unwrap();
    ok(&out, "verify");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("checked blocks: 2"),
        "expected both fixture blocks to be checked; stdout: {stdout}"
    );
    assert!(
        stdout.contains("checked ref-log records: 2"),
        "expected both fixture ref-log records to be checked; stdout: {stdout}"
    );
    assert!(
        stdout.contains("ref publication issues: 0"),
        "expected zero publication issues; stdout: {stdout}"
    );

    let out = prikk(&repo).arg("doctor").output().unwrap();
    ok(&out, "doctor");
    let doctor_stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        doctor_stdout.contains("errors=0, warnings=0"),
        "expected a clean doctor report; stdout: {doctor_stdout}"
    );

    let _ = std::fs::remove_dir_all(&repo);
}
