[workspace]
resolver = "3"
members = [
    "crates/prikk-cli",
    "crates/prikk-crypto",
    "crates/prikk-error",
    "crates/prikk-hash",
    "crates/prikk-object",
    "crates/prikk-replay",
    "crates/prikk-store",
    "tools/release-policy",
]
default-members = [
    "crates/prikk-cli",
    "crates/prikk-crypto",
    "crates/prikk-error",
    "crates/prikk-hash",
    "crates/prikk-object",
    "crates/prikk-replay",
    "crates/prikk-store",
]

[workspace.package]
version         = "0.18.2"
edition         = "2024"
rust-version    = "1.85"
license             = "Apache-2.0"
authors             = ["nabbisen"]
repository          = "https://github.com/nabbisen/prikk"
homepage            = "https://nabbisen.github.io/prikk/"
categories          = ["algorithms"]
keywords            = ["vcs"]

[workspace.dependencies]
prikk-crypto                = { version = "0.18.2", path = "crates/prikk-crypto" }
prikk-error                 = { version = "0.18.2", path = "crates/prikk-error" }
prikk-hash                  = { version = "0.18.2", path = "crates/prikk-hash" }
prikk-object                = { version = "0.18.2", path = "crates/prikk-object" }
prikk-replay                = { version = "0.18.2", path = "crates/prikk-replay" }
prikk-store                 = { version = "0.18.2", path = "crates/prikk-store" }

ed25519-dalek               = "2"
getrandom                   = "0.2"
rustix                      = { version = "1", features = ["fs"] }
sha2                        = "0.10"

# Testing
proptest                    = "1"


[workspace.lints.rust]
unsafe_code         = "forbid"
missing_docs        = "warn"

[workspace.lints.clippy]
unwrap_used         = "warn"
expect_used         = "warn"
indexing_slicing    = "warn"
