[package]
name        = "prikk-replay"
description = "Workspace-internal replay and lifecycle semantics for Prikk."
readme      = "README.md"
version.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
authors.workspace       = true
repository.workspace    = true

[dependencies]
prikk-error                 = { workspace = true }
prikk-hash                  = { workspace = true }
prikk-object                = { workspace = true }

[lints]
workspace = true
