[package]
name        = "prikk-hash"
description = "Prikk hash primitives."
readme      = "README.md"
version.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
authors.workspace       = true
repository.workspace    = true

[dependencies]
sha2 = { workspace = true }

[lints]
workspace = true
