[package]
name        = "prikk"
description = "Prikk CLI initial scaffold."
readme      = "../../README.md"
version.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
authors.workspace       = true
repository.workspace    = true
homepage.workspace      = true
categories.workspace    = true
keywords.workspace      = true

[dependencies]
prikk-hash                  = { workspace = true }
prikk-object                = { workspace = true }
prikk-store                 = { workspace = true }

[lints]
workspace = true
