[package]
name        = "prikk-crypto"
description = "Prikk cryptographic primitives (v1 Ed25519 signing and verification)."
readme      = "README.md"
version.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
license.workspace       = true
authors.workspace       = true
repository.workspace    = true

[dependencies]
prikk-error                 = { workspace = true }

ed25519-dalek               = { workspace = true }
getrandom                   = { workspace = true }

[lints]
workspace = true
