[book]
title = "Prikk"
authors = ["nabbisen"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/nabbisen/prikk"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
